server:
 port: 8999


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1
    username: root
    password: 123123123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect


