spring:
  datasource:
    url: jdbc:mysql:/springboot?characterEncoding=utf-8
    username: root
    password: 123123
    driver-class-name:
people:
  username: 小李
  password: 111
  gender: 男
  age: 18

server:
  port: 8089
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
